language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./econtrol.php sys install
  - ./econtrol.php sys check
  - ./econtrol.php tasks
  - ./econtrol.php jobs
  - ./econtrol.php logs
